<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net10.0</TargetFramework><ImplicitUsings>enable</ImplicitUsings><Nullable>enable</Nullable></PropertyGroup>
  <ItemGroup>
    <Compile Remove="FakeTgrep\**" />
    <ProjectReference Include="..\Core\TgrepGui.Core.csproj" />
    <ProjectReference Include="FakeTgrep\FakeTgrep.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>
</Project>
